### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by ECNUHP** [seanie12/nqg#18]
hello , I found a issue when decoding, can you offer some suggestion for this issue? Thank you in advance.

File "main.py", line 16, in <module>
    main()
  File "main.py", line 12, in main
    beamsearcher.decode()
  File "/opt/lang.huo/mybot/neural_question_generation/infenrence.py", line 70, in decode
    best_question = self.beam_search(src_seq, ext_src_seq, src_len, tag_seq)
  File "/opt/lang.huo/mybot/neural_question_generation/infenrence.py", line 90, in beam_search
    enc_mask = torch.ByteTensor(src_seq == zeros)

**Comment by ECNUHP** [comment]
> hello , I found a issue when decoding, can you offer some suggestion for this issue? Thank you in advance.
> 


Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 12, in main
    beamsearcher.decode()
  File "/opt/lang.huo/mybot/neural_question_generation/infenrence.py", line 70, in decode
    best_question = self.beam_search(src_seq, ext_src_seq, src_len, tag_seq)
  File "/opt/lang.huo/mybot/neural_question_generation/infenrence.py", line 90, in beam_search
    enc_mask = torch.ByteTensor(src_seq == zeros)
TypeError: expected Byte (got Bool)

**Comment by seanie12** [comment]
enc_mask = (src_seq == zeros).byte() would work.
