### ISSUE TITLE
CUDA ERROR occured in training

### ISSUE THREAD

**Issue by lydia07** [seanie12/nqg#23]
The comandline information is as follows:
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [604,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 9, in main
    trainer.train()
  File "/data/hyx/workspace/test/neural-question-generation/trainer.py", line 81, in train
    batch_loss = self.step(train_data)
  File "/data/hyx/workspace/test/neural-question-generation/trainer.py", line 124, in step
    enc_outputs, enc_states = self.model.encoder(src_seq, src_len, tag_seq)
  File "/data/hyx/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/hyx/workspace/test/neural-question-generation/model.py", line 56, in forward
    packed = pack_padded_sequence(embedded, src_len, batch_first=True)
  File "/data/hyx/miniconda3/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 223, in pack_padded_sequence
    lengths = torch.as_tensor(lengths, dtype=torch.int64)
RuntimeError: CUDA error: device-side assert triggered
----------------------------------------------------------------------
This problem is quite strange because I used to train this model sucessfully.
To solve this problem, I tried to use cpu for more error information, however I couldn't use it. 
Could you please offer me some help? Do you know anything about this issue?
Thanks a lot!

**Comment by seanie12** [comment]
Maybe some ids for token are greater than vocab size. I ve updated my repo. Please run the code again
